### PR TITLE
chore: rebuild shiki

### PR DESCRIPTION
**Pull request by cyyynthia**
Includes changes from https://github.com/Vap0r1ze/shiki/pull/1

### CODE REVIEW

**Comment by Vap0r1ze** [comment]
I'd actually prefer if you could rebuild with the main shiki as my changes have been merged since shikijs/shiki#140. There might be slight differences in the API but you can check with the PR to see if something differs.

You might want to refer to a specific commit in the makefile though

**Comment by cyyynthia** [comment]
> as my changes have been merged

Well the thing is, I made a PR to your fork that adds caching to fix some performance issues as described there. While it yields good results and is a simple fix, I don't think it's a good way and is more of a hotfix than anything. I guess shiki isn't really optimized to have lots of jobs thrown at it like in the plugin

> You might want to refer to a specific commit in the makefile though

Figured that wouldn't be super necessary as a commit is needed to update the shiki.min.js anyway, I just quickly made it to make the life of generating that file easier

**Comment by Vap0r1ze** [comment]
Fair points, seems like my fork is the way to go for now, will merge ASAP

**Comment by Vap0r1ze** [comment]
I'll be on mobile for the night so if you think you're hotfix is immediately ready for use, make another PR (unless you've included it already)

**Comment by cyyynthia** [comment]
It was already included & tested

**Pull request merged**
